### PR TITLE
Automated build and testing using github actions

### PR DESCRIPTION
**Pull request by aph42**
I've given a first go at updating the automated build and test script to use github actions. Also they work. The current action builds using python versions 3.7-3.12, and the tests are passing on all versions (I think), though there are plenty of warnings that could use squashing.

I've had to update some of the code to get these to work and a few unrelated changes have snuck in (e.g. a bump to max_array_size in the default pygrc file).

### CODE REVIEW

**Comment by neishm** [comment]
This looks promising!  Is there a way to see the logs from the builds?  I can't seem to see anything from here.  I'm also above seeing the message 

> Continuous integration has not been set up
> 
> [GitHub Actions](https://github.com/features/actions) and [several other apps](https://github.com/marketplace/category/continuous-integration) can be used to automatically catch bugs and enforce style.

but I thought that was what this merge was giving us?

**Comment by aph42** [comment]
I am able to follow the build logs in real time here, for instance:

https://github.com/aph42/pygeode/actions/workflows/build-and-test.yml

Are you able to see that?

**Comment by neishm** [comment]
> I am able to follow the build logs in real time here, for instance:
> 
> https://github.com/aph42/pygeode/actions/workflows/build-and-test.yml
> 
> Are you able to see that?

Ok, thanks I can see the build logs as well.  I just thought they would show up within this merge request as well.  Maybe because this branch is from your personal repository, so it hasn't started the actions integration on the pygeode project yet?  Like, maybe after this merge than any future merge requests would show the build status...

**Comment by aph42** [comment]
Oh I see - that would be helpful. I don't know.

**Comment by aph42** [comment]
This kind of fell of the map this summer for me with a lot of other things going on, but I'd like to pick this up again to move towards a 1.4.2rc1 release. Given the discussion above I'm going to go ahead and merge this as a first step.

**Pull request merged**
