### PR TITLE
Cartopy

### PR DESCRIPTION
**Pull request by aph42**
I think the cartopy support in this branch has advanced far enough that it is worth merging into the main branch. There is also some unrelated stuff in this branch that I've put there because I've been too lazy to deal with this more properly. It passes all the tests in my python 2 setup but there's enough going on I'd like someone else to take a look to make sure I don't break anything too severely.

I'm motivated to do this in part because I'd like to be able to include this in a new minor release so that we can have cartopy support for the workshop at the end of the month.

### CODE REVIEW

**Comment by aph42** [comment]
I am a bit nervous about the fact that there are no conflicts reported, but the changes look clean to me, so I'll go ahead and submit this for review. To be a bit more specific about some of the additional changes: there is a new 'cumulative sum' variable, there are some improvements to the stats module (both in how it plays with progress bars and in some of the edge cases), and some further improvements to error reporting for open_multi variables.

**Comment by neishm** [comment]
Thanks for working on this.  I will try to have a look through it over the next few days.  A couple of comments / questions so far:

1. I tried running the `buildGFS()` command, but am getting the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygeode/tutorial.py", line 89, in buildGFS
    d = pyg.open(u, format = 'netcdf4', dimtypes = dict(isobaric = pyg.Pres), \
  File "/pygeode/formats/__init__.py", line 162, in open
    return format.open(filename, value_override=value_override, dimtypes=dimtypes, \
  File "pygeode/formats/netcdf4.py", line 223, in open
    f = nc.Dataset(filename,"r")
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -72] NetCDF: Malformed or inaccessible DAP DDS: b'https://www.ncei.noaa.gov/thredds/dodsC/gfs-g4-anl-files/201902/20190220/gfsanl_4_20190220_0000_000.grb2'
```
Maybe it's another problem with strings on Python3? Don't have Python2 on this machine to test out that hypothesis.  Does it work for you?

2. I noticed `.grb2` extensions are now handled by the netcdf4 module.  I'm wondering if this might cause confusion if a user tries to open a local GRIB2 file with that extension?

3. I tried doing a quick plot test after installing cartopy, by running the following:
```
import pygeode as pyg
from pygeode.tutorial import t1
pyg.showvar(t1.Temp)
from matplotlib import pyplot as pl
pl.show()
```
but nothing's showing up on the screen.  I'll try again tomorrow when I'm more awake... I'm probably missing something.

**Comment by aph42** [comment]
I've removed the buildGFS() tutorial dataset and the association of 'grb2' extensions to the netcdf4 format module. Unfortunately the NCEI THREDDS server has somehow changed its configuration so that it doesn't work anymore. It would be good to have something like this in the future but I don't want to make this merge contingent on getting that working.

I don't understand why the plot shouldn't be showing up. One possibly related issue that I am going to continue looking at this evening is how the plotting stuff interacts with different matplotlib backends - the matplotlib API for identifying what capabilities the current backend has (i.e. whether or not it's interactive) isn't great. Hence issues with generating the docs and with jupyter notebooks. But if you're in an interactive ipython session I don't see why that should be an issue.

**Comment by neishm** [comment]
Trying to plot directly with matplotlib gives the following warning:
```
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```
So I think it is an issue with the backend for my local machine.  Everything was installed in a clean virtualenv, so I'm trying to figure out what went wrong with my setup...

**Comment by aph42** [comment]
Maybe a stray matplotlibrc file somewhere? Odd for a clean install though.

**Comment by neishm** [comment]
Figured it out after some searching online.  Apparently the tk package has to be available on the host system (installed through the Linux distro, not through pip).  In my case, I had to run `sudo apt install python3-tk`.  Seems to work now!  Map is showing up, with the lat/lon axes and grid lines.

**Comment by aph42** [comment]
With regards to cumsum and integrate - these compute 'indefinite integrals' in the sense that the output variable will have the same axes as the input variable, unlike the reductions of `sum` or `mean`.
That being said, they are a bit like `interpolate` in that they require data from the whole of the integration axis, even if you are only interested in a small subset, which can lead to inefficiencies. This is also the case with interpolate. It probably does make sense to make that clear in their doc strings.

**Pull request merged**
